<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>MacAC.Sim</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MacAC.Client" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MacAC.Core\MacAC.Core.csproj" />
  </ItemGroup>
</Project>
