namespace MacAC.Sim.Comms;

public enum ClientDirectiveId
{
    LifestoneRecall,

    MarketplaceRecall,
    PkArenaRecall,
    PkLiteArenaRecall,
    EnterPkLite,
    HouseRecall,
    MansionRecall,
    QueryAge,
    QueryBirth,
    ToggleFrameRate,
    TogglePersistentDaylight,
    RenderOption,
    ToggleUiLock,
    ShowVersion,
    ShowLocation,
    ShowLastCorpseLocation,
    Die,
    ClearChat,

    ChatLogFile,
    SaveUi,
    LoadUi,
    SaveAutoUi,
    LoadAutoUi,
    Away,
    Consent,
    Emote,
    ListEmotes,
    Friends,
    FriendsAdd,
    FriendsRemove,
    Squelch,
    Unsquelch,
    Filter,
    Unfilter,
    ListMessageTypes,
    FillComponents,

    Endurance,
    /// <summary>@speaker - fixed deprecation notice ("see @allegiance officer").</summary>
    Speaker,
    SetChatTitle,
    ChatToggle,
    /// <summary>@notell on|off - global Tell squelch toggle (message type 3).</summary>
    NoTellToggle,
    JoinChannel,
    LeaveChannel,
    Permit,
    /// <summary>@hslist &lt;type&gt; / "@house available" - list houses available for purchase.</summary>
    HouseAvailableList,
    IndexChannels,
    ListChannel,
    OnChannel,
    OffChannel,
    AllegianceHometown,
    /// <summary>"@allegiance info &lt;name&gt;" - request allegiance member info.</summary>
    AllegianceInfo,
    AllegianceBoot,
    AllegianceBan,
    AllegianceChat,
    AllegianceBroadcast,
    AllegianceOfficer,
    AllegianceOfficerTitle,
    AllegianceName,
    AllegianceLock,
    AllegianceHouse,
    AllegianceMotd,
    HouseAbandon,
    HouseOpenStatus,
    HouseStorage,
    HouseBoot,
    HouseBootAll,
    HouseGuests,
    HouseHooks,
    AllegianceUnrecognizedSubcommand,

    HouseUnrecognizedSubcommand,
}
