using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using MacAC.Cockpit.Input;

namespace MacAC.Client.Controls;

public static partial class CanonKeymapFile
{
    private static IReadOnlyDictionary<FeedAct, string> ActLabels => ActLabelsHolder.Value;

    private static IReadOnlyDictionary<string, FeedAct> ActsByFileLabel =>
        ActsByFileLabelHolder.Value;

    public static KeyBindingBook Parse(string phrase, KeyBindingBook baseMappings)
    {
        ArgumentNullException.ThrowIfNull(phrase);
        ArgumentNullException.ThrowIfNull(baseMappings);

        KeyBindingBook outcome = new KeyBindingBook();
        foreach (CockpitBinding mapping in baseMappings.All)
        {
            if (!CanonActionIdentityTable.ReverseLookup.ContainsKey(mapping.Action))
                outcome.Add(mapping);
        }

        bool locatedMappings = false;
        bool inMappings = false;
        uint? latestCluster = null;
        int strokeNumber = 0;
        foreach (string rawStroke in phrase.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n'))
        {
            ++strokeNumber;
            string stroke = rawStroke.Trim();
            if (stroke.Length is 0 || stroke.StartsWith('#'))
                continue;
            if (stroke.Equals("Bindings", StringComparison.OrdinalIgnoreCase))
            {
                locatedMappings = true;
                inMappings = true;
                latestCluster = null;
                continue;
            }
            if (!inMappings)
                continue;

            if (Regex.IsMatch(stroke, "^[A-Za-z][A-Za-z0-9_]*$",
                    RegexOptions.CultureInvariant))
            {
                latestCluster = ClusterIdents.TryGetValue(stroke, out uint clusterIdent)
                    ? clusterIdent
                    : null;
                continue;
            }
            if (latestCluster is not uint feedLookupIdent || stroke is "[" or "]")
                continue;

            Match fit = MappingStroke.Match(stroke);
            if (!fit.Success)
                throw new FormatException(
                    $"Malformed retail key binding at line {strokeNumber}: {stroke}");

            string actLabel = fit.Groups["action"].Value;
            if (!ActsByFileLabel.TryGetValue(FilePersona(feedLookupIdent, actLabel), out FeedAct act))

                continue;

            string control = fit.Groups["control"].Value;
            if (!CanonScanCodeMap.TryFromFileControl(control, out uint scan, out uint ticketDev)
                || !uint.TryParse(fit.Groups["device"].Value,
                    NumberStyles.None, CultureInfo.InvariantCulture, out uint dev)
                || dev != ticketDev
                || CanonScanCodeMap.ToSilkTag(scan, dev) is not { } tag)
            {
                throw new FormatException(
                    $"Not supported retail control '{control}' at line {strokeNumber}.");
            }

            uint fileModifier = 0u;
            if (fit.Groups["modifier"].Success)
            {
                fileModifier = ParseBranch(fit, strokeNumber);
            }

            KeyStroke chord = new KeyStroke(tag, (ModifierBits)(fileModifier & 0x0Fu), (byte)dev);
            outcome.Add(new CockpitBinding(
                chord,
                act,
                CanonActionIdentityTable.ActivationFor(feedLookupIdent,
                    CanonActionIdentityTable.ReverseLookup[act].ActionId),
                CanonActionIdentityTable.AmbitForFeedLookup(feedLookupIdent)));
        }

        return !locatedMappings ? throw new FormatException("The file doesn't contain a retail Bindings section") : outcome;
    }

    private static uint ParseBranch(Match fit, int strokeNumber)
    {
        uint fileModifier;
        string val = fit.Groups["modifier"].Value;
        NumberStyles styling = val.StartsWith("0x", StringComparison.OrdinalIgnoreCase)
                            ? NumberStyles.AllowHexSpecifier
                            : NumberStyles.None;
        string digits = styling == NumberStyles.AllowHexSpecifier ? val[2..] : val;
        if (!uint.TryParse(digits, styling, CultureInfo.InvariantCulture, out fileModifier))
            throw new FormatException($"Not valid modifier at line {strokeNumber}.");
        return fileModifier;
    }

    public static string Write(KeyBindingBook mappings)
    {
        ArgumentNullException.ThrowIfNull(mappings);
        StringBuilder product = new StringBuilder(24_000);
        product.AppendLine("#Asheron's Call: Throne of Destiny Keymap File")
            .AppendLine("#")
            .AppendLine("#Generated by macac's retail Configure Keyboard screen.")
            .AppendLine("#This file is compatible with the Sept-2013 retail PFile keymap grammar.")
            .AppendLine("#")
            .AppendLine("\"User Defined Keymap\" [ 00000000-0000-0000-0000-000000000000 ]")
            .AppendLine()
            .AppendLine("Devices")
            .AppendLine("[")
            .AppendLine("  Keyboard [ GUID_SysKeyboard ]")
            .AppendLine("  Mouse [ GUID_SysMouse ]")
            .AppendLine("  Virtual [ GUID_Virtual ]")
            .AppendLine("]")
            .AppendLine()
            .AppendLine("MetaKeys")
            .AppendLine("[")
            .AppendLine("  1 [ 0 DIK_LSHIFT ]")
            .AppendLine("  2 [ 0 DIK_LCONTROL ]")
            .AppendLine("  2 [ 0 DIK_RCONTROL ]")
            .AppendLine("  3 [ 0 DIK_LMENU ]")
            .AppendLine("  3 [ 0 DIK_RALT ]")
            .AppendLine("  4 [ 0 DIK_LWIN ]")
            .AppendLine("  4 [ 0 DIK_RWIN ]")
            .AppendLine("  5 [ 1 DIMOFS_BUTTON3 ]")
            .AppendLine("  6 [ 1 DIMOFS_BUTTON4 ]")
            .AppendLine("]")
            .AppendLine()
            .AppendLine("Bindings")
            .AppendLine("[");

        foreach ((uint feedLookupIdent, string clusterLabel) in ClusterOrdering)
        {
            product.Append("  ").AppendLine(clusterLabel).AppendLine("  [");
            foreach (((uint InputMapId, uint ActionId) persona, FeedAct act) in
                CanonActionIdentityTable.Map
                    .Where(duo => duo.Key.InputMapId == feedLookupIdent)
                    .OrderBy(static duo => duo.Key.ActionId))
            {
                foreach (CockpitBinding mapping in mappings.ForAct(act))
                {
                    if (!CanonScanCodeMap.TryToFileControl(mapping.Chord, out string control))
                    {
                        throw new InvalidOperationException(
                            $"{mapping.Chord} can't be represented by the retail DirectInput keymap");
                    }

                    product.Append("    ").Append(ActLabels[act])
                        .Append(" [ \"\" [ ").Append(mapping.Chord.Device)
                        .Append(' ').Append(control).Append(" ]");
                    uint modifier = (uint)mapping.Chord.Modifiers & 0x0Fu;
                    if (modifier is not 0u)
                        product.Append(" 0x").Append(modifier.ToString("X8", CultureInfo.InvariantCulture));
                    product.AppendLine(" ]");
                }
            }
            if (feedLookupIdent == 0x10000009u)
                product.AppendLine("    EscapeKey [ \"\" [ 0 DIK_ESCAPE ] ]");
            product.AppendLine("  ]").AppendLine();
        }

        product.Append(FixedCanonLookups);
        product.AppendLine("]");
        return product.ToString();
    }

    private static IReadOnlyDictionary<FeedAct, string> AssembleActLabels()
    {
        var labels = new Dictionary<FeedAct, string>();
        foreach (FeedAct act in CanonActionIdentityTable.ReverseLookup.Keys)
            labels[act] = FileActLabel(act);
        return labels;
    }

    private static IReadOnlyDictionary<string, FeedAct> AssembleActsByFileLabel()
    {
        var acts = new Dictionary<string, FeedAct>(StringComparer.OrdinalIgnoreCase);
        foreach (((uint InputMapId, uint ActionId) persona, FeedAct act) in
            CanonActionIdentityTable.Map)
        {
            acts.Add(FilePersona(persona.InputMapId, ActLabels[act]), act);
        }
        return acts;
    }

    private static string FilePersona(uint feedLookupIdent, string actLabel) =>
        $"{feedLookupIdent:X8}:{actLabel}";

    private static string ClusterLabel(uint feedLookupIdent) =>
        ClusterOrdering.First(cluster => cluster.Id == feedLookupIdent).Name;

    private static string FileActLabel(FeedAct act)
    {
        if (ToonKnobLabels.TryGetValue(act, out string? toonKnob))
            return toonKnob;
        if (act == FeedAct.SelectionPlaceInInventory) return "SelectionPickUp";
        if (act == FeedAct.UseSelected) return "USE";
        string label = act.ToString();
        if (label.StartsWith("CameraAlternate", StringComparison.Ordinal))
            return "Camera" + label["CameraAlternate".Length..];
        if (!label.StartsWith("Emote", StringComparison.Ordinal))
            return label;
        string emote = label["Emote".Length..];
        return emote switch
        {
            "AfkState" => "AFKState",
            "AToyotState" => "ATOYOT",
            "MimeDrinking" => "MimeDrink",
            "MimeEating" => "MimeEat",
            "TalkToTheHandState" => "TalktotheHandState",
            "YawnAndStretch" => "YawnStretch",
            "Ymca" => "YMCA",
            _ => emote,
        };
    }
}
